### ISSUE TITLE
Timeout when running the script

### ISSUE THREAD

**Issue by katox** [prisma/graal-compatibility#1]
I like the idea so I wanted to try the suite but the script doesn't work for me.

1. I had to install "expect" because it's no longer a standard part of Ubuntu.
2. I had to change akkaHttp in dependencies from "mbtest" to "10.1.5" or I get an unresolved dependency.

Still running the script gives no reasonable output and ends with a timeout. See the `results.txt` below.

```text
$ ./check-compatibility.sh 


Packaging...

[info] Loading project definition from /home/katox/prg/graal/graal-compatibility/project
[info] Compiling 1 Scala source to /home/katox/prg/graal/graal-compatibility/project/target/scala-2.12/sbt-1.0/classes ...
[info] Done compiling.
[info] Loading settings for project root from build.sbt ...
[info] Set current project to graal-compatibility (in build file:/home/katox/prg/graal/graal-compatibility/)
[success] Total time: 0 s, completed Oct 8, 2018 10:11:30 AM
[info] Loading project definition from /home/katox/prg/graal/graal-compatibility/project
[info] Loading settings for project root from build.sbt ...
[info] Set current project to graal-compatibility (in build file:/home/katox/prg/graal/graal-compatibility/)
[info] Updating scalajHttp...
[info] Updating scalaLogging...
[info] Updating java8Compat...
[info] Updating postgres...
[info] Updating snakeYML...
[info] Updating evoInflector...
[info] Updating logstash...
[info] Updating slick...
[info] Done updating.
[info] Updating mysql...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Run 'evicted' to see detailed eviction warnings
[info] Updating akka...
[info] Done updating.
[info] Updating amqp...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Run 'evicted' to see detailed eviction warnings
[info] Updating scalaUri...
[info] Done updating.
[info] Updating jwt...
[info] Done updating.
[info] Updating other...
[info] Done updating.
[info] Updating parserCombinators...
[info] Done updating.
[info] Updating mariaDb...
[info] Done updating.
[info] Updating librato...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Run 'evicted' to see detailed eviction warnings
[info] Updating playJson...
[info] Done updating.
[info] Updating finagle...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Run 'evicted' to see detailed eviction warnings
[info] Updating jettyServer...
[info] Done updating.
[info] downloading https://repo1.maven.org/maven2/com/typesafe/akka/akka-http_2.12/10.1.5/akka-http_2.12-10.1.5.jar ...
[info] downloading https://repo1.maven.org/maven2/com/typesafe/akka/akka-http-core_2.12/10.1.5/akka-http-core_2.12-10.1.5.jar ...
[info] downloading https://repo1.maven.org/maven2/com/typesafe/akka/akka-parsing_2.12/10.1.5/akka-parsing_2.12-10.1.5.jar ...
[info] 	[SUCCESSFUL ] com.typesafe.akka#akka-parsing_2.12;10.1.5!akka-parsing_2.12.jar (711ms)
[info] 	[SUCCESSFUL ] com.typesafe.akka#akka-http_2.12;10.1.5!akka-http_2.12.jar (1084ms)
[info] 	[SUCCESSFUL ] com.typesafe.akka#akka-http-core_2.12;10.1.5!akka-http-core_2.12.jar (1975ms)
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Run 'evicted' to see detailed eviction warnings
[info] Done updating.
[info] Compiling 1 Scala source to /home/katox/prg/graal/graal-compatibility/scalaLogging/target/scala-2.12/classes ...
[info] Compiling 1 Scala source to /home/katox/prg/graal/graal-compatibility/logstash/target/scala-2.12/classes ...
[info] Done updating.
[info] Compiling 1 Scala source to /home/katox/prg/graal/graal-compatibility/scalajHttp/target/scala-2.12/classes ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Run 'evicted' to see detailed eviction warnings
[info] Compiling 1 Scala source to /home/katox/prg/graal/graal-compatibility/postgres/target/scala-2.12/classes ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Run 'evicted' to see detailed eviction warnings
[info] Compiling 1 Scala source to /home/katox/prg/graal/graal-compatibility/java8Compat/target/scala-2.12/classes ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Run 'evicted' to see detailed eviction warnings
[info] Compiling 1 Scala source to /home/katox/prg/graal/graal-compatibility/snakeYML/target/scala-2.12/classes ...
[info] Done updating.
[info] Compiling 1 Scala source to /home/katox/prg/graal/graal-compatibility/evoInflector/target/scala-2.12/classes ...
[info] Compiling 1 Scala source to /home/katox/prg/graal/graal-compatibility/parserCombinators/target/scala-2.12/classes ...
[info] Done compiling.
[info] Done compiling.
[info] Done compiling.
[info] Compiling 1 Scala source to /home/katox/prg/graal/graal-compatibility/other/target/scala-2.12/classes ...
[info] Compiling 1 Scala source to /home/katox/prg/graal/graal-compatibility/slick/target/scala-2.12/classes ...
[info] Compiling 1 Scala source to /home/katox/prg/graal/graal-compatibility/jwt/target/scala-2.12/classes ...
[info] Done compiling.
[info] Compiling 1 Scala source to /home/katox/prg/graal/graal-compatibility/scalaUri/target/scala-2.12/classes ...
[info] Done compiling.
[info] Compiling 1 Scala source to /home/katox/prg/graal/graal-compatibility/amqp/target/scala-2.12/classes ...
[info] Done compiling.
[info] Compiling 1 Scala source and 2 Java sources to /home/katox/prg/graal/graal-compatibility/akka/target/scala-2.12/classes ...
[info] Done compiling.
[info] Done compiling.
[info] Done compiling.
[info] Done compiling.
[info] Updating ...
[info] Packaging /home/katox/prg/graal/graal-compatibility/snakeYML/target/scala-2.12/snakeyml_2.12-0.1.0-SNAPSHOT.jar ...
[info] Packaging /home/katox/prg/graal/graal-compatibility/evoInflector/target/scala-2.12/evoinflector_2.12-0.1.0-SNAPSHOT.jar ...
[info] Packaging /home/katox/prg/graal/graal-compatibility/scalajHttp/target/scala-2.12/scalajhttp_2.12-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Packaging /home/katox/prg/graal/graal-compatibility/jwt/target/scala-2.12/jwt_2.12-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Done packaging.
[info] Done packaging.
[info] Packaging /home/katox/prg/graal/graal-compatibility/logstash/target/scala-2.12/logstash_2.12-0.1.0-SNAPSHOT.jar ...
[info] Packaging /home/katox/prg/graal/graal-compatibility/amqp/target/scala-2.12/amqp_2.12-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Done packaging.
[info] Packaging /home/katox/prg/graal/graal-compatibility/postgres/target/scala-2.12/postgres_2.12-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Packaging /home/katox/prg/graal/graal-compatibility/slick/target/scala-2.12/slick_2.12-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Packaging /home/katox/prg/graal/graal-compatibility/scalaLogging/target/scala-2.12/scalalogging_2.12-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Compiling 1 Scala source to /home/katox/prg/graal/graal-compatibility/mysql/target/scala-2.12/classes ...
[info] Done compiling.
[info] Compiling 1 Scala source to /home/katox/prg/graal/graal-compatibility/librato/target/scala-2.12/classes ...
[info] Compiling 1 Scala source to /home/katox/prg/graal/graal-compatibility/jettyServer/target/scala-2.12/classes ...
[info] Compiling 1 Scala source to /home/katox/prg/graal/graal-compatibility/finagle/target/scala-2.12/classes ...
[info] Done compiling.
[info] Compiling 1 Scala source to /home/katox/prg/graal/graal-compatibility/play-json/target/scala-2.12/classes ...
[info] Done compiling.
[info] Packaging /home/katox/prg/graal/graal-compatibility/scalaUri/target/scala-2.12/scalauri_2.12-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Compiling 1 Scala source to /home/katox/prg/graal/graal-compatibility/mariaDb/target/scala-2.12/classes ...
[info] Done compiling.
[info] Done compiling.
[info] Packaging /home/katox/prg/graal/graal-compatibility/other/target/scala-2.12/other_2.12-0.1.0-SNAPSHOT.jar ...
[info] Packaging /home/katox/prg/graal/graal-compatibility/mysql/target/scala-2.12/mysql_2.12-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Done packaging.
[info] Done compiling.
[info] Packaging /home/katox/prg/graal/graal-compatibility/java8Compat/target/scala-2.12/java8compat_2.12-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Packaging /home/katox/prg/graal/graal-compatibility/jettyServer/target/scala-2.12/jettyserver_2.12-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Packaging /home/katox/prg/graal/graal-compatibility/librato/target/scala-2.12/librato_2.12-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Packaging /home/katox/prg/graal/graal-compatibility/play-json/target/scala-2.12/playjson_2.12-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Done compiling.
[info] Done compiling.
[info] Packaging /home/katox/prg/graal/graal-compatibility/finagle/target/scala-2.12/finagle_2.12-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Packaging /home/katox/prg/graal/graal-compatibility/parserCombinators/target/scala-2.12/parsercombinators_2.12-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Done compiling.
[info] Packaging /home/katox/prg/graal/graal-compatibility/mariaDb/target/scala-2.12/mariadb_2.12-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Done compiling.
[info] Packaging /home/katox/prg/graal/graal-compatibility/akka/target/scala-2.12/akka_2.12-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.3/scala-library-2.12.3.jar ...
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.3/scala-reflect-2.12.3.jar ...
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.3/scala-compiler-2.12.3.jar ...
[info] downloading https://repo1.maven.org/maven2/jline/jline/2.14.4/jline-2.14.4.jar ...
[info] 	[SUCCESSFUL ] jline#jline;2.14.4!jline.jar (500ms)
[info] 	[SUCCESSFUL ] org.scala-lang#scala-reflect;2.12.3!scala-reflect.jar (2254ms)
[info] 	[SUCCESSFUL ] org.scala-lang#scala-library;2.12.3!scala-library.jar (3358ms)
[info] 	[SUCCESSFUL ] org.scala-lang#scala-compiler;2.12.3!scala-compiler.jar (4541ms)
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Run 'evicted' to see detailed eviction warnings
[info] Packaging /home/katox/prg/graal/graal-compatibility/target/scala-2.12/graal-compatibility_2.12-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[success] Total time: 17 s, completed Oct 8, 2018 10:11:55 AM



Generating classpaths... 

[info] Loading project definition from /home/katox/prg/graal/graal-compatibility/project
[info] Loading settings for project root from build.sbt ...
[info] Set current project to graal-compatibility (in build file:/home/katox/prg/graal/graal-compatibility/)
[success] Total time: 1 s, completed Oct 8, 2018 10:12:03 AM
akka-actor_2.12-2.5.12.jar
akka-http_2.12-10.1.5.jar
akka-http-core_2.12-10.1.5.jar
akka-parsing_2.12-10.1.5.jar
akka-protobuf_2.12-2.5.12.jar
akka-stream_2.12-2.5.12.jar
amqp-client-4.1.0.jar
bcpkix-jdk15on-1.57.jar
bcprov-jdk15on-1.57.jar
bugsnag-3.0.2.jar
caffeine-2.5.5.jar
commons-lang-2.6.jar
config-1.3.2.jar
cuid-java-0.1.1.jar
evo-inflector-1.2.jar
finagle-base-http_2.12-6.44.0.jar
finagle-core_2.12-6.44.0.jar
finagle-http_2.12-6.44.0.jar
finagle-http2_2.12-6.44.0.jar
finagle-netty4_2.12-6.44.0.jar
finagle-netty4-http_2.12-6.44.0.jar
finagle-toggle_2.12-6.44.0.jar
guava-19.0.jar
HikariCP-2.5.1.jar
jackson-annotations-2.8.9.jar
jackson-core-2.8.9.jar
jackson-databind-2.8.9.jar
jackson-datatype-jdk8-2.8.9.jar
jackson-datatype-jsr310-2.8.9.jar
jackson-module-paranamer-2.8.4.jar
jackson-module-scala_2.12-2.8.4.jar
java-dogstatsd-client-2.3.jar
javax.servlet-api-3.1.0.jar
jetty-http-9.3.0.v20150612.jar
jetty-io-9.3.0.v20150612.jar
jetty-server-9.3.0.v20150612.jar
jetty-util-9.3.0.v20150612.jar
joda-convert-1.7.jar
joda-time-2.9.9.jar
jsr305-3.0.0.jar
jwt-core_2.12-0.14.1.jar
jwt-core-impl_2.12-0.14.1.jar
librato-java-2.1.0.jar
logback-classic-1.1.7.jar
logback-core-1.1.7.jar
logstash-logback-encoder-4.7.jar
macro-compat_2.12-1.1.1.jar
mariadb-java-client-2.1.2.jar
mysql-connector-java-8.0.12.jar
netty-3.10.1.Final.jar
netty-buffer-4.1.9.Final.jar
netty-codec-4.1.9.Final.jar
netty-codec-http2-4.1.9.Final.jar
netty-codec-http-4.1.9.Final.jar
netty-codec-socks-4.1.9.Final.jar
netty-common-4.1.9.Final.jar
netty-handler-4.1.9.Final.jar
netty-handler-proxy-4.1.9.Final.jar
netty-resolver-4.1.9.Final.jar
netty-transport-4.1.9.Final.jar
netty-transport-native-epoll-4.1.9.Final-linux-x86_64.jar
paranamer-2.8.jar
parboiled_2.12-2.1.4.jar
play-functional_2.12-2.6.8.jar
play-json_2.12-2.6.8.jar
postgresql-42.2.2.jar
protobuf-java-2.6.0.jar
reactive-streams-1.0.2.jar
scalactic_2.12-3.0.4.jar
scala-java8-compat_2.12-0.8.0.jar
scalaj-http_2.12-2.3.0.jar
scala-library-2.12.3.jar
scala-logging_2.12-3.7.0.jar
scala-parser-combinators_2.12-1.1.0.jar
scala-reflect-2.12.3.jar
scala-uri_2.12-1.1.1.jar
shapeless_2.12-2.3.3.jar
slf4j-api-1.7.25.jar
slick_2.12-3.2.3.jar
slick-hikaricp_2.12-3.2.3.jar
slick-joda-mapper_2.12-2.3.0.jar
snakeyaml-1.19.jar
spray-json_2.12-1.3.3.jar
ssl-config-core_2.12-0.2.3.jar
svm.jar
util-app_2.12-6.43.0.jar
util-cache_2.12-6.43.0.jar
util-codec_2.12-6.43.0.jar
util-collection_2.12-6.43.0.jar
util-core_2.12-6.43.0.jar
util-function_2.12-6.43.0.jar
util-hashing_2.12-6.43.0.jar
util-jvm_2.12-6.43.0.jar
util-lint_2.12-6.43.0.jar
util-logging_2.12-6.43.0.jar
util-registry_2.12-6.43.0.jar
util-security_2.12-6.43.0.jar
util-stats_2.12-6.43.0.jar
util-tunable_2.12-6.43.0.jar


Testing projects...

########################################################################################################


Testing /home/katox/prg/graal/graal-compatibility/akka/target/scala-2.12/akka_2.12-0.1.0-SNAPSHOT.jar

########################################################################################################


Building WITHOUT ReportUnsupportedElementsAtRuntime flag...

Build on Server(pid: 22541, port: 39907)
SendBuildRequest [
-task=com.oracle.svm.hosted.NativeImageGeneratorRunner
-imagecp
/home/katox/sw/graalvm-ce-1.0.0-rc7/jre/lib/svm/builder/svm.jar:/home/katox/sw/graalvm-ce-1.0.0-rc7/jre/lib/svm/builder/objectfile.jar:/home/katox/sw/graalvm-ce-1.0.0-rc7/jre/lib/svm/builder/pointsto.jar:/home/katox/sw/graalvm-ce-1.0.0-rc7/jre/lib/jvmci/jvmci-hotspot.jar:/home/katox/sw/graalvm-ce-1.0.0-rc7/jre/lib/jvmci/jvmci-api.jar:/home/katox/sw/graalvm-ce-1.0.0-rc7/jre/lib/jvmci/graal-management.jar:/home/katox/sw/graalvm-ce-1.0.0-rc7/jre/lib/jvmci/graal.jar:/home/katox/sw/graalvm-ce-1.0.0-rc7/jre/lib/boot/graaljs-scriptengine.jar:/home/katox/sw/graalvm-ce-1.0.0-rc7/jre/lib/boot/graal-sdk.jar:/home/katox/sw/graalvm-ce-1.0.0-rc7/jre/lib/svm/library-support.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/akka-actor_2.12-2.5.12.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/akka-http_2.12-10.1.5.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/akka-http-core_2.12-10.1.5.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/akka-parsing_2.12-10.1.5.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/akka-protobuf_2.12-2.5.12.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/akka-stream_2.12-2.5.12.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/amqp-client-4.1.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/bcpkix-jdk15on-1.57.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/bcprov-jdk15on-1.57.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/bugsnag-3.0.2.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/caffeine-2.5.5.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/commons-lang-2.6.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/config-1.3.2.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/cuid-java-0.1.1.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/evo-inflector-1.2.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/finagle-base-http_2.12-6.44.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/finagle-core_2.12-6.44.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/finagle-http_2.12-6.44.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/finagle-http2_2.12-6.44.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/finagle-netty4_2.12-6.44.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/finagle-netty4-http_2.12-6.44.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/finagle-toggle_2.12-6.44.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/guava-19.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/HikariCP-2.5.1.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/jackson-annotations-2.8.9.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/jackson-core-2.8.9.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/jackson-databind-2.8.9.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/jackson-datatype-jdk8-2.8.9.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/jackson-datatype-jsr310-2.8.9.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/jackson-module-paranamer-2.8.4.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/jackson-module-scala_2.12-2.8.4.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/java-dogstatsd-client-2.3.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/javax.servlet-api-3.1.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/jetty-http-9.3.0.v20150612.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/jetty-io-9.3.0.v20150612.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/jetty-server-9.3.0.v20150612.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/jetty-util-9.3.0.v20150612.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/joda-convert-1.7.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/joda-time-2.9.9.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/jsr305-3.0.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/jwt-core_2.12-0.14.1.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/jwt-core-impl_2.12-0.14.1.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/librato-java-2.1.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/logback-classic-1.1.7.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/logback-core-1.1.7.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/logstash-logback-encoder-4.7.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/macro-compat_2.12-1.1.1.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/mariadb-java-client-2.1.2.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/mysql-connector-java-8.0.12.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/netty-3.10.1.Final.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/netty-buffer-4.1.9.Final.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/netty-codec-4.1.9.Final.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/netty-codec-http2-4.1.9.Final.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/netty-codec-http-4.1.9.Final.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/netty-codec-socks-4.1.9.Final.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/netty-common-4.1.9.Final.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/netty-handler-4.1.9.Final.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/netty-handler-proxy-4.1.9.Final.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/netty-resolver-4.1.9.Final.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/netty-transport-4.1.9.Final.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/netty-transport-native-epoll-4.1.9.Final-linux-x86_64.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/paranamer-2.8.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/parboiled_2.12-2.1.4.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/play-functional_2.12-2.6.8.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/play-json_2.12-2.6.8.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/postgresql-42.2.2.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/protobuf-java-2.6.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/reactive-streams-1.0.2.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/scalactic_2.12-3.0.4.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/scala-java8-compat_2.12-0.8.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/scalaj-http_2.12-2.3.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/scala-library-2.12.3.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/scala-logging_2.12-3.7.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/scala-parser-combinators_2.12-1.1.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/scala-reflect-2.12.3.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/scala-uri_2.12-1.1.1.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/shapeless_2.12-2.3.3.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/slf4j-api-1.7.25.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/slick_2.12-3.2.3.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/slick-hikaricp_2.12-3.2.3.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/slick-joda-mapper_2.12-2.3.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/snakeyaml-1.19.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/spray-json_2.12-1.3.3.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/ssl-config-core_2.12-0.2.3.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/svm.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/util-app_2.12-6.43.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/util-cache_2.12-6.43.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/util-codec_2.12-6.43.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/util-collection_2.12-6.43.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/util-core_2.12-6.43.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/util-function_2.12-6.43.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/util-hashing_2.12-6.43.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/util-jvm_2.12-6.43.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/util-lint_2.12-6.43.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/util-logging_2.12-6.43.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/util-registry_2.12-6.43.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/util-security_2.12-6.43.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/util-stats_2.12-6.43.0.jar:/home/katox/prg/graal/graal-compatibility/target/lib_managed/util-tunable_2.12-6.43.0.jar:/home/katox/prg/graal/graal-compatibility/akka/target/scala-2.12/akka_2.12-0.1.0-SNAPSHOT.jar
-H:Path=/home/katox/prg/graal/graal-compatibility
-H:+EnableAllSecurityServices
-H:RerunClassInitialization=javax.net.ssl.SSLContext
-H:IncludeResources=reference.conf,version.conf
-H:+JNI
-H:Class=Main
-H:CLibraryPath=/home/katox/sw/graalvm-ce-1.0.0-rc7/jre/lib/svm/clibraries/linux-amd64
-H:ReflectionConfigurationFiles=/home/katox/prg/graal/graal-compatibility/akka_reflection_config.json
-H:Name=main
]
[main:22541]    classlist:  12,155.66 ms
[main:22541]        (cap):     939.71 ms
[main:22541]        setup:   1,750.87 ms
loaded the config:
{"akka":{"library-extensions":[],"ssl-config":{"default":true}}}
[]
[main:22541]   (typeflow):  15,601.40 ms
[main:22541]    (objects):  16,631.71 ms
[main:22541]   (features):     571.70 ms
[main:22541]     analysis:  34,015.87 ms
[main:22541]     universe:   1,369.63 ms
[main:22541]      (parse):   2,836.57 ms
[main:22541]     (inline):   4,103.28 ms
[main:22541]    (compile):  16,471.99 ms
[main:22541]      compile:  24,865.72 ms
[main:22541]        image:   2,541.26 ms
[main:22541]        write:     623.05 ms
[main:22541]      [total]:  77,428.23 ms



Running...

Akka
hello back at you
huh?
[INFO] [10/08/2018 10:13:22.555] [main] [AkkaSSLConfig(akka://HelloSystem)] ssl-config.default is true, using the JDK's default SSLContext
WARNING: The sunec native library could not be loaded.
Exception in thread "main" java.lang.NullPointerException
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:215)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at sun.security.ssl.TrustManagerFactoryImpl.getCacertsKeyStore(TrustManagerFactoryImpl.java:226)
	at sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:50)
	at javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:250)
	at com.typesafe.sslconfig.akka.AkkaSSLConfig.validateDefaultTrustManager(AkkaSSLConfig.scala:138)
	at com.typesafe.sslconfig.akka.AkkaSSLConfig.<init>(AkkaSSLConfig.scala:74)
	at com.typesafe.sslconfig.akka.AkkaSSLConfig$.createExtension(AkkaSSLConfig.scala:29)
	at com.typesafe.sslconfig.akka.AkkaSSLConfig$.createExtension(AkkaSSLConfig.scala:19)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:913)
	at akka.actor.ExtensionId.apply(Extension.scala:79)
	at akka.actor.ExtensionId.apply$(Extension.scala:78)
	at com.typesafe.sslconfig.akka.AkkaSSLConfig$.apply(AkkaSSLConfig.scala:24)
	at com.typesafe.sslconfig.akka.AkkaSSLConfig$.apply(AkkaSSLConfig.scala:19)
	at akka.http.scaladsl.HttpExt.<init>(Http.scala:60)
	at akka.http.scaladsl.Http$.createExtension(Http.scala:1111)
	at akka.http.scaladsl.Http$.createExtension(Http.scala:880)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:913)
	at akka.actor.ExtensionId.apply(Extension.scala:79)
	at akka.actor.ExtensionId.apply$(Extension.scala:78)
	at akka.http.scaladsl.Http$.apply(Http.scala:1106)
	at Main$.testAkkaHttp(Main.scala:61)
	at Main$.main(Main.scala:36)
	at Main.main(Main.scala)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:163)
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
Timeout after 10 seconds



Done

########################################################################################################


Competed in 134 ✅
```

**Comment by dpetrick** [comment]
Apologies for the dependency issue, that is a remnant of local development. The timeout / error is expected, as the suite is not working right now. Our goal is to make it work :)

We'll clean up and work on all of this soon. Stay tuned.
